### PR TITLE
Checking for 'func' command works on MacOS too

### PR DESCRIPTION
**Pull request by eashi**
This PR changes the code that checks for the `func` command in PATH so that it works on both Windows and MacOS.

The current code only works on Windows: 

1. The path separator is a semicolon (doesn't work on Mac). This PR changes the code so that it uses the `Path.PathSeparator` rather than hard-coding a semicolon or a colon. For more information check: https://learn.microsoft.com/en-us/dotnet/api/system.io.path.pathseparator?view=net-7.0
2. The check assumes that the command file `func` has the extension suffix `.exe`. This is true on Windows, but not on MacOS. This PR searches for both cases to support both Windows and MacOS.
3. The `Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine)` returns null because the option passed `EnvironmentVariableTarget.Machine` fails on MacOS. Removing the option fixes it and shouldn't cause any unexpected behaviours. For more infomration check https://learn.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=net-7.0

### CODE REVIEW

**Review by mark-abrams — DISMISSED** [review]
Thanks for the contribution. I've only used the framework on a Windows OS, so it is good to see that someone is using on a MacOS. Have you run into any other problems or issues when using the testing framework on MacOS?

**Review by mark-abrams — APPROVED** [review]

**Comment by eashi** [comment]
Thanks for accepting the PR. I haven't came across any other issues, but will keep you posted. Cheers.

**Comment by mark-abrams** [comment]
Hi @eashi , I have uploaded version [1.6.0 of LogicAppUnit to Nuget](https://www.nuget.org/packages/LogicAppUnit]). This includes your changes in PR #14 and also PR #15 for support for the MacOS platform. Thank you for your contribution.

**Comment by eashi** [comment]
This is great news, thanks Mark for the great project and active maintenance.

**Pull request merged**
